In [3]:
import pandas as pd
import numpy as np

# Create a date range and sample DataFrame
date_range = pd.date_range(start="2023-01-01", periods=10, freq='D')
df = pd.DataFrame({
    "date": date_range,
    "sales": np.random.randint(100, 500, size=10)
})

# Extract parts of the date
df["year"] = df["date"].dt.year                  # Extract year
df["month"] = df["date"].dt.month                # Extract month
df["day"] = df["date"].dt.day                    # Extract day
df["weekday"] = df["date"].dt.day_name()         # Name of the day
df["week_number"] = df["date"].dt.isocalendar().week  # Week of the year

# Add/Subtract time
df["plus_7_days"] = df["date"] + pd.Timedelta(days=7)
df["minus_3_days"] = df["date"] - pd.Timedelta(days=3)

# Format date to string
df["formatted"] = df["date"].dt.strftime('%d-%b-%Y')

# Check if the date is on a weekend
df["is_weekend"] = df["weekday"].isin(["Saturday", "Sunday"])

# Create a time delta column
df["delta_days"] = (df["plus_7_days"] - df["date"]).dt.days

# Display result
df

,date,sales,year,month,day,weekday,week_number,plus_7_days,minus_3_days,formatted,is_weekend,delta_days
0,2023-01-01,199,2023,1,1,Sunday,52,2023-01-08,2022-12-29,01-Jan-2023,True,7
1,2023-01-02,262,2023,1,2,Monday,1,2023-01-09,2022-12-30,02-Jan-2023,False,7
2,2023-01-03,222,2023,1,3,Tuesday,1,2023-01-10,2022-12-31,03-Jan-2023,False,7
3,2023-01-04,321,2023,1,4,Wednesday,1,2023-01-11,2023-01-01,04-Jan-2023,False,7
4,2023-01-05,394,2023,1,5,Thursday,1,2023-01-12,2023-01-02,05-Jan-2023,False,7
5,2023-01-06,284,2023,1,6,Friday,1,2023-01-13,2023-01-03,06-Jan-2023,False,7
6,2023-01-07,293,2023,1,7,Saturday,1,2023-01-14,2023-01-04,07-Jan-2023,True,7
7,2023-01-08,227,2023,1,8,Sunday,1,2023-01-15,2023-01-05,08-Jan-2023,True,7
8,2023-01-09,355,2023,1,9,Monday,2,2023-01-16,2023-01-06,09-Jan-2023,False,7
9,2023-01-10,193,2023,1,10,Tuesday,2,2023-01-17,2023-01-07,10-Jan-2023,False,7